// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsn_dYDkSntCUyCxLoyCPRVAsrkn63Zmw',
    appId: '1:169469903904:web:e267b71474a2cb0c8d2845',
    messagingSenderId: '169469903904',
    projectId: 'flash-chat-b67ab',
    authDomain: 'flash-chat-b67ab.firebaseapp.com',
    storageBucket: 'flash-chat-b67ab.appspot.com',
    measurementId: 'G-4R6V44BY6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLZiSXSFiHkPSfYtGpaBNzy8Qqvys_mn4',
    appId: '1:169469903904:android:c6c5c052c1588bb78d2845',
    messagingSenderId: '169469903904',
    projectId: 'flash-chat-b67ab',
    storageBucket: 'flash-chat-b67ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGgqqbh7TCcxNBhvXhwTfLLbxY_QGgyRc',
    appId: '1:169469903904:ios:ebf378965b0125748d2845',
    messagingSenderId: '169469903904',
    projectId: 'flash-chat-b67ab',
    storageBucket: 'flash-chat-b67ab.appspot.com',
    iosClientId: '169469903904-dd2d7lga1j4bbs3slomsarmtin9qha58.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
